### ISSUE TITLE
Secret key exposed?

### ISSUE THREAD

**Issue by mondaysunrise** [quolpr/harika#218]
https://github.com/quolpr/harika/blob/ceda77ed97905dfd399a868b83fc7ecbb00fd1ed/docker-compose.local.yml#L44

https://aws.amazon.com/blogs/security/what-to-do-if-you-inadvertently-expose-an-aws-access-key/

**Comment by quolpr** [comment]
Actually it's a randomg secret key 🤔 But I plan to make the generation of docker-compose.yml, so nobody will reuse the same keys.

Thank you for the report!
